config/routes.rb
# encoding: utf-8
Mdd::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root :to => 'search#index'

  resources :keyword_categories
  resources :keywords
  resources :sheets

  resources :search, only: [:index]
end

app/models/keyword_category.rb
# encoding: utf-8
# == Schema Information
#
# Table name: keyword_categories
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class KeywordCategory < ActiveRecord::Base
  has_many :keywords, dependent: :destroy
  accepts_nested_attributes_for :keywords

  validates :name, :presence => true

  attr_accessible :name

  def self.skills
    KeywordCategory.where(name: 'Pôles de compétence').first
  end
end

app/controllers/keyword_categories_controller.rb
# encoding: utf-8
class KeywordCategoriesController < InheritedResources::Base
  before_filter :authenticate_user!
  authorize_resource
  respond_to :html

  def index
    redirect_to keywords_path
  end

  def destroy
    destroy! do
      redirect_to :back
    end
  end

  protected

  def collection
    @keyword_categories ||= end_of_association_chain.page(params[:page])
  end

end

app/views/keyword_categories/_form.html.erb
<%= simple_form_for resource, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input  :name, :input_html => { :class => 'span3' } %>
  <div class='form-actions'>
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/keyword_categories/edit.html.erb
<article class='keyword-category'>

  <ul class='breadcrumb row'>
    <li>
      <%= link_to t('nav.keyword_categories.index'), keywords_path %>
      <span class='divider'>/</span>
      <li class='active'>
        <%= t('nav.keyword_categories.edit') %>
      </li>
    </li>
  </ul>

  <header class='page-header row'>
    <h1 class='pull-left'>
      <%= t('.title') %>
    </h1>
  </header>

  <%= render :partial => 'form' %>

</article>

app/views/keyword_categories/new.html.erb
<article class='keyword-category'>

  <ul class='breadcrumb row'>
    <li>
      <%= link_to t('nav.keyword_categories.index'), keywords_path %>
      <span class='divider'>/</span>
      <li class='active'>
        <%= t('nav.keyword_categories.new') %>
      </li>
    </li>
  </ul>

  <header class='page-header row'>
    <h1 class='pull-left'>
      <%= t('.title') %>
    </h1>
  </header>

  <%= render :partial => 'form' %>

</article>

app/views/keyword_categories/show.html.erb
<article class='keyword-category'>

  <ul class='breadcrumb row'>
    <li>
      <%= link_to t('nav.keyword_categories.index'), keyword_categories_path %>
      <span class='divider'>/</span>
      <li class='active'>
        <%= resource.name %>
      </li>
    </li>
  </ul>

  <header class='page-header row'>
    <h1 class='pull-left'><%= resource.name %></h1>
    <p class='pull-right'>
      <%= link_to t('actions.keyword_categories.edit'), edit_keyword_category_path(resource), :class => 'btn' %>
      <%= link_to t('actions.keywords.new'), new_keyword_path(keyword_category_id: resource.id), :class => 'btn btn-primary' %>
    </p>
  </header>

  <section class='row'>
    <table class='table table-bordered table-striped'>
      <tr>
        <th><%= t('.keyword') %></th>
        <th><%= t('.actions') %></th>
      </tr>
      <% resource.keywords.each do |keyword| %>
      <tr>
        <td><%= link_to keyword.name, keyword_path(keyword) %></td>
        <td>
          <%= link_to t('actions.keywords.edit'), edit_keyword_path(keyword), :class => 'btn btn-small' %>
          <%= link_to t('actions.keywords.delete'), keyword_path(keyword), method: :delete, confirm: t('actions.confirm_delete'), :class => 'btn btn-danger btn-small' %>
        </td>
      </tr>
      <% end %>
    </table>
    <%= paginate collection %>
  </section>

</article>