config/routes.rb
# encoding: utf-8
Mdd::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root :to => 'search#index'

  resources :keyword_categories
  resources :keywords
  resources :sheets

  resources :search, only: [:index]
end

app/models/sheet.rb
# encoding: utf-8
# == Schema Information
#
# Table name: sheets
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :text
#  level       :integer
#  up_to_date  :boolean
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Sheet < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  LEVELS = [1, 2, 3]

  has_and_belongs_to_many :keywords
  has_many   :histories, dependent: :destroy, as: :subject

  accepts_nested_attributes_for :keywords

  validates :title,       presence: true
  validates :description, presence: true
  validates :level,       presence: true, inclusion: { in: LEVELS }
  validate  :at_least_one_skills_keyword

  attr_accessible :title, :description, :level, :up_to_date, :keyword_ids

  # Search

  mapping do
    indexes :id,          type: :integer, index: :not_analyzed
    indexes :title,       type: :string,  analyzer: :french
    indexes :description, type: :string,  analyzer: :french
    indexes :up_to_date,  type: :boolean, index: :not_analyzed
    indexes :level,       type: :integer, index: :not_analyzed
    indexes :updated_at,  type: :date,    index: :not_analyzed
    indexes :tags,        type: :string,  index: :not_analyzed
  end

  def to_indexed_json
    {
      id:          self.id,
      title:       self.title,
      description: self.description,
      up_to_date:  self.up_to_date,
      level:       self.level,
      updated_at:  self.updated_at,
      tags:        self.keywords.map(&:name)
    }.to_json
  end

  def self.search(params = {})
    s = Tire::Search::Search.new(tire.index.name, load: true)

    # Query
    if params[:query].present?

      # Fix bad queries
      params[:query] = params[:query].split().map { |q| q.end_with?(':') ? q.chomp(':') : q }.join(' ')

      s.query { string params[:query] }
    else
      s.query { all }
    end

    # Filters
    [:up_to_date, :level].each do |term|
      s.filter :term, {term => params[term]} if params[term].present?
    end

    # Tags
    tags = Array(params[:tags]) + Array(params['most-used-keywords'])
    s.filter :and, tags.map { |tag| {term: {tags: tag}} } if tags.present?

    # Date
    case params[:updated]
    when 'today'
      s.filter :range, updated_at: {gte: Date.today, lt: Date.tomorrow}
    when 'yesterday'
      s.filter :range, updated_at: {gte: Date.yesterday, lt: Date.today}
    when 'this-week'
      s.filter :range, updated_at: {gte: Date.today.beginning_of_week, lt: Date.tomorrow}
    when 'this-month'
      s.filter :range, updated_at: {gte: Date.today.beginning_of_month, lt: Date.tomorrow}
    end

    # Facets
    s.facet 'tags', global: true do
      terms :tags, exclude: KeywordCategory.skills.keywords.map(&:name)
    end

    # Pagination
    if params[:pagination]
      page     = params[:page] ? (params[:page].to_i - 1) : 0
      per_page = params[:per_page] || Kaminari.config.default_per_page

      s.from page * per_page
      s.size per_page
    end

    s.sort { by params[:sort_by] || :updated_at, :desc}

    s
  end

  def self.clear_index!
    self.tire.index.delete
    self.tire.index.create mappings: self.tire.mapping_to_hash, settings: self.tire.settings
  end

  def self.refresh_index!
    self.tire.index.refresh
  end

  private

  def at_least_one_skills_keyword
    # Check if any keyword belongs to the skills category
    unless self.keywords.any? { |keyword| KeywordCategory.skills.keywords.include?(keyword) }
      errors.add(:keywords, I18n.t("errors.one_skill_keyword"))
    end
  end

end

app/controllers/sheets_controller.rb
# encoding: utf-8
class SheetsController < InheritedResources::Base
  before_filter :authenticate_user!
  authorize_resource
  respond_to :html

  helper_method :search_results, :previous_result, :next_result
  
  def show
    @sheet = Sheet.find(params[:id])
    if request.path != sheet_path(@sheet) && Rails.env != "test"
       redirect_to @sheet, status: :moved_permanently
    end
  end


  def create
    create! do |success, error|
      success.any do
        resource.histories << History.create(user: current_user, subject: resource, action: 'create')
        redirect_to sheet_path(resource)
      end
    end
  end

  def update
    update! do |success, error|
      success.any do
        resource.histories << History.create(user: current_user, subject: resource, action: 'update')
        redirect_to sheet_path(resource)
      end
    end
  end

  def search_results(params)
    return @results if @results
    params[:pagination] = false
    @results = Sheet.search(params).perform.results
  end

  def previous_result
    params  = session[:last_search] || {}
    results = search_results(params).to_a
    i = results.index(resource)
    (i && i >= 1) ? results[i - 1] : nil
  end

  def next_result
    params  = session[:last_search] || {}
    results = search_results(params).to_a
    i = results.index(resource)
    (i && i < (results.size - 1)) ? results[i + 1] : nil
  end

  protected

  def collection
    @sheets ||= end_of_association_chain.page(params[:page])
  end



end

app/helpers/sheet_helper.rb
module SheetHelper

  def last_search?
    !session[:last_search].nil?
  end

end

app/views/sheets/_form.html.erb
<%= simple_form_for resource, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title, :input_html => { :class => 'span3' } %>
  <%= f.input :level, as: :radio_buttons, collection: Sheet::LEVELS %>
  <%= f.input :up_to_date %>
  <% if resource.errors.has_key?(:keywords) %>
    <div class='alert alert-error'>
      <%= f.error :keywords %>
    </div>
  <% end %>
  <% KeywordCategory.all.each do |keyword_category| %>
    <h6><%= keyword_category.name %></h6>
    <%= f.association :keywords, collection: keyword_category.keywords, as: :check_boxes, label: false, error: false %>
  <% end %>
  <%= f.input :description, :as => :ckeditor, label: false %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/sheets/edit.html.erb
<article class='sheet new'>

  <ul class='breadcrumb'>
    <li>
      <%= link_to t('nav.sheets.index'), search_index_path %>
      <span class='divider'>/</span>
      <li>
        <%= link_to resource.title, sheet_path(resource) %>
      </li>
      <li class='active'>
        <span class='divider'>/</span>
        <%= t('nav.sheets.edit') %>
      </li>
    </li>
  </ul>

  <%= render :partial => 'form' %>

</article>

app/views/sheets/index.html.erb
<article class='sheets'>

  <header class='page-header clearfix'>
    <h1 class='pull-left'><%= t('.title') %></h1>
    <%= link_to t('actions.sheets.new'), new_sheet_path, :class => 'btn btn-primary pull-right' %>
  </header>

  <section>
    <table class='table table-bordered table-striped'>
      <tr>
        <th><%= t('.keywords') %></th>
        <th><%= t('.sheet') %></th>
      </tr>
      <%= render partial: "shared/sheets", locals: {sheets: collection} %>
    </table>
    <%= paginate collection %>
  </section>

</article>

app/views/sheets/new.html.erb
<article class='sheet new'>

  <ul class='breadcrumb'>
    <li>
      <%= link_to t('nav.sheets.index'), search_index_path %>
      <span class='divider'>/</span>
      <li class='active'>
        <%= t('nav.sheets.new') %>
      </li>
    </li>
  </ul>

  <%= render :partial => 'form' %>

</article>

app/views/sheets/show.html.erb
<header class='navbar-inner'>
  <p class='pull-left'>
    <%= link_to search_index_path, :class => 'btn', :title => 'Retour' do %>
      <i class='icon-chevron-left'></i>
    <% end %>
  </p>
  <h1 class='pull-left'><%= resource.title %></h1>
  <div class='pull-right'>
    <% if last_search? %>
      <% if previous_result %>
        <%= link_to sheet_path(previous_result), :class => 'btn' do %>
          <i class='icon-arrow-left'></i>
        <% end %>
      <% else %>
        <%= link_to '#', :class => 'btn disabled' do %>
          <i class='icon-arrow-left'></i>
        <% end %>
      <% end %>
      <% if next_result %>
        <%= link_to sheet_path(next_result), :class => 'btn' do %>
          <i class='icon-arrow-right'></i>
        <% end %>
      <% else %>
        <%= link_to '#', :class => 'btn disabled' do %>
          <i class='icon-arrow-right'></i>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <aside class='level_<%= resource.level %>'>
    <p class='picture'><%= image_tag("no_picture.png") %></p>
    <div class='metadata'>
      <% resource.keywords.each do |keyword| %>
        <span class='badge'><%= keyword.name %></span>
      <% end %>
    </div>
    <div class='history'>
      <ul class='unstyled'>
      <% resource.histories.last(10).reverse.each do |history| %>
        <li><%= t(".histories.#{history.action}", user: history.user.name, time: l(history.created_at, format: :short)) %></li>
      <% end %>
      </ul>
    </div>
  </aside>

<article class='sheet'>
  <article>
    <section class='description'>
      <%= raw(resource.description) %>
    </section>
    <div class='actions'>
      <%= link_to edit_sheet_path(resource), :class => 'btn btn-mini btn-primary' do %>
        <i class='icon-pencil icon-white'></i>
      <% end %>
      <%= link_to sheet_path(resource), method: :delete, confirm: t('actions.confirm_delete'), :class => 'btn btn-mini' do %>
        <i class='icon-trash'></i>
      <% end %>
    </div>
  </article>
</article>