config/routes.rb
# encoding: utf-8
Mdd::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root :to => 'search#index'

  resources :keyword_categories
  resources :keywords
  resources :sheets

  resources :search, only: [:index]
end

app/models/keyword.rb
# encoding: utf-8
# == Schema Information
#
# Table name: keywords
#
#  id                  :integer         not null, primary key
#  name                :string(255)
#  keyword_category_id :integer
#  created_at          :datetime        not null
#  updated_at          :datetime        not null
#

class Keyword < ActiveRecord::Base
  belongs_to :keyword_category
  has_and_belongs_to_many :sheets

  validates :name,             :presence => true
  validates :keyword_category, :presence => true

  attr_accessible :name, :keyword_category, :keyword_category_id
end

app/controllers/keywords_controller.rb
# encoding: utf-8
class KeywordsController < InheritedResources::Base
  before_filter :authenticate_user!
  authorize_resource
  respond_to :html

  def new
    @keyword = Keyword.new(keyword_category_id: params[:keyword_category_id])
  end

  protected

  def collection
    @keywords ||= end_of_association_chain.page(params[:page])
  end

end

app/views/keywords/_form.html.erb
<%= simple_form_for resource, :html => { :class => 'form-horizontal' } do |f| %>
  <% if resource.new_record? %>
    <%= f.association :keyword_category %>
  <% end %>
  <%= f.input  :name, :input_html => { :class => 'span3' } %>
  <div class='form-actions'>
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<article class='keyword'>

  <ul class='breadcrumb row'>
    <li>
      <%= link_to t('nav.keywords.index'), keywords_path %>
      <span class='divider'>/</span>
      <li class='active'>
        <%= t('actions.keywords.edit') %>
      </li>
    </li>
  </ul>

  <header class='page-header row'>
    <h1 class='pull-left'><%= t('.title') %></h1>
  </header>

  <%= render :partial => 'form' %>

</article>

app/views/keywords/index.html.erb
<article class='keywords'>

  <header class='page-header row'>
    <h1 class='pull-left'><%= t('.title') %></h1>
    <div class='pull-right'>
      <%= link_to t('actions.keywords.new'), new_keyword_path, :class => 'btn btn-primary' %>
      <%= link_to t('actions.keyword_categories.new'), new_keyword_category_path, :class => 'btn btn-primary' %>
    </div>
  </header>

  <section class='row'>
    <% KeywordCategory.all.each do |category| %>
      <table class='table table-bordered table-striped'>
        <tr>
          <th><%= link_to category.name, keyword_category_path(category) %></th>
          <th>
            <%= link_to t('actions.keyword_categories.edit'), edit_keyword_category_path(category), :class => 'btn btn-small' %>
            <%= link_to t('actions.keyword_categories.delete'), keyword_category_path(category), method: :delete, confirm: t('actions.confirm_delete'), :class => 'btn btn-danger btn-small' %>
          </th>
        </tr>
        <% category.keywords.each do |keyword| %>
        <tr>
          <td><%= link_to keyword.name, keyword_path(keyword) %></td>
          <td>
            <%= link_to t('actions.keywords.edit'), edit_keyword_path(keyword), :class => 'btn btn-small' %>
            <%= link_to t('actions.keywords.delete'), keyword_path(keyword), method: :delete, confirm: t('actions.confirm_delete'), :class => 'btn btn-danger btn-small' %>
          </td>
        </tr>
        <% end %>
      </table>
    <% end %>
    <%= paginate collection %>
  </section>

</article>

app/views/keywords/new.html.erb
<article class='keyword'>

  <ul class='breadcrumb row'>
    <li>
      <%= link_to t('nav.keywords.index'), keywords_path %>
      <span class='divider'>/</span>
      <li class='active'>
        <%= t('nav.keywords.new') %>
      </li>
    </li>
  </ul>

  <header class='page-header row'>
    <h1 class='pull-left'><%= t('.title') %></h1>
  </header>

  <%= render :partial => 'form' %>

</article>

app/views/keywords/show.html.erb
<article class='keyword'>

  <ul class='breadcrumb row'>
    <li>
      <%= link_to t('nav.keywords.index'), keywords_path %>
      <span class='divider'>/</span>
      <li class='active'>
        <%= resource.name %>
      </li>
    </li>
  </ul>

  <header class='page-header row'>
    <h1 class='pull-left'><%= resource.name %></h1>
    <p class='pull-right'>
      <%= link_to t('actions.edit'), edit_keyword_path(resource), :class => 'btn' %>
      <%= link_to t('actions.sheets.new'), new_sheet_path, :class => 'btn btn-primary' %>
    </p>
  </header>

  <section class='row'>
    <table class='table table-bordered table-striped'>
      <tr>
        <th><%= t('.sheet') %></th>
        <th><%= t('.actions') %></th>
      </th>
    </tr>
      <% resource.sheets.each do |sheet| %>
      <tr>
        <td><%= link_to sheet.title, sheet_path(sheet) %></td>
        <td>
          <%= link_to t('actions.sheets.edit'), edit_sheet_path(sheet), :class => 'btn btn-small' %>
          <%= link_to t('actions.sheets.delete'), sheet_path(sheet), method: :delete, confirm: t('actions.confirm_delete'), :class => 'btn btn-danger btn-small' %>
        </td>
      </tr>
      <% end %>

    </table>
  </section>

  <%= paginate collection %>

</article>